http:
  routers:
    website-legacy:
      entryPoints:
        - http
      rule: "Host(`lysz210.name`)"
      middlewares:
        - https-redirect@file
      service: cv-legacy
    website:
      entryPoints:
        - https
      service: s3-bucket-website
      rule: "Host(`lysz210.name`)"
      tls:
        certresolver: le
  services:
    s3-bucket-website:
      loadBalancer:
        servers:
          - url: http://lysz210.name.s3-website.eu-south-1.amazonaws.com
    website-legacy:
        loadBalancer:
          servers:
            - port: 80
